### ISSUE TITLE
Style switching seems broken

### ISSUE THREAD

**Issue by Tzky** [korobi/weblog#9]
When accessing the Korobi weblog, it defaults to the dark theme. Hitting the theme button once gives the expected result (dark->light change). However switching back doesn't seem to work, as the button won't have any effect after the first hit. When reloading via F5 afterwards, the page is dark again.

I'm using FF 42.0, no adblocker/scriptblocker or similar. FF prints this in it's console:
`TypeError: DISQUS.next is undefined` in `main.js:42`.

**Comment by bendem** [comment]
Looks like [the hack I used to reload disqus](https://github.com/korobi/weblog/blob/4f843e6b33d0b7b5ca175dbc48bb3c45f2d5ed87/js/main.js#L42) broke. Using the [new documented api](https://help.disqus.com/customer/portal/articles/472107-using-disqus-on-ajax-sites) `DISQUS.reset({ reload: true });` should fix it.
